### PR TITLE
 show all aliases on overview page

### PR DESCRIPTION
**Pull request by Rassyan**

### CODE REVIEW

**Comment by rtkgjacobs** [comment]
I've missed seeing all aliases shown on the overview page, older versions used to do this 👍 

However if others object to this, perhaps a compromise can be that a UI element can expand/collapse when more than one (click on it) or a mouse-over view of all of them worse case?

**Comment by Rassyan** [comment]
> I've missed seeing all aliases shown on the overview page, older versions used to do this 👍
> 
> However if others object to this, perhaps a compromise can be that a UI element can expand/collapse when more than one (click on it) or a mouse-over view of all of them worse case?

I just make the smallest possible change to the code I can. However, I aggre to your suggestion that a compromise is better.

**Comment by lmenezes** [comment]
hey there. sorry, but displaying all aliases be default is not a great move. some people do have several aliases for the same index, and this makes the whole ui kind of messed up.

having the top 2 or 3 displayed by default, and an option to expand/collapse to see the rest would be fine. if you would like to give this a try, that would be great.

**Comment by Rassyan** [comment]
> hey there. sorry, but displaying all aliases be default is not a great move. some people do have several aliases for the same index, and this makes the whole ui kind of messed up.
> 
> having the top 2 or 3 displayed by default, and an option to expand/collapse to see the rest would be fine. if you would like to give this a try, that would be great.

pleasure to give that a try, added an option at left row to expand/collapse to see all aliases/single alias.

**Pull request closed without merging**
