### PR TITLE
implemented nodes page

### PR DESCRIPTION
**Pull request by adamlepkowski**
Created nodes page without only one feature (sorting by a node name - I will implement it later).

image

### CODE REVIEW

**Comment by lmenezes** [comment]
hey @adamlepkowski 

thanks a lot for the PR, I have been pretty busy lately and haven't really had the time to check on the project. I will try to review this today and merge as soon as possible :)

**Comment by xbgmsharp** [comment]
Nice work, exactly what I'm looking for! Would love to see this merge with a new release to include the latest change.

**Comment by adamlepkowski** [comment]
@lmenezes are you going to merge it? or you have some remarks? 
@xbgmsharp thanks :)

**Comment by lmenezes** [comment]
@adamlepkowski hey adam!
I still haven't had the time to look into it, I'm sorry. But yes, this will get merged!

I expect I will have a couple of hours tomorrow, and would like to then review and merged this(changes can be made after merge, that's not a problem).

Thanks again for contributing, and if you feel adventurous we could have a chat about other stuff you could work on :)

**Comment by lmenezes** [comment]
@adamlepkowski sorry, just merged this by mistake :(

I took a look at it, and the front end looks good, but on the backend side it would be better not to reuse the same API call as the overview page, as this loads way more information than whats necessary to render the nodes list page.

Ideally, we would create a new API that returns only the data needed to render that page, and also in a format that makes it easier to do so.

I believe most of the info needed here is available through the cat api.

**Comment by adamlepkowski** [comment]
@lmenezes I thought about creating a new API but I decided to reuse existing one because it had all required data and even more and I wasn't sure about your approach  ;) 

Currently, I'm doing overtime but I will try to improve it during a weekend.

I can help you with other stuff just send me an email at adam.lepkowski@gmail.com

**Comment by xbgmsharp** [comment]
Some here as mention by @adamlepkowski the overview API includes ll required data for both Nodes and Indices page.

**Pull request merged**
