### PR TITLE
implemented indices page

### PR DESCRIPTION
**Pull request by xbgmsharp**
Base on pull #7 , created indices page without sorting feature. 
screen_shot_2016-11-04_at_3_32_27_pm

### CODE REVIEW

**Comment by lmenezes** [comment]
@xbgmsharp could you please squash + rebase this against master?

**Comment by lmenezes** [comment]
@xbgmsharp I meant it more for the squashing than rebasing. I'm also taking a look at #16 , and the comments there apply to this one as well.

Ideally, we would have a new API on the backend to render this page. Fetching all shard data and etc only to render a list with the indices is not really great. I'm pretty sure the cat api already has most of this information, if not all.

In doing so, we can also make sure that the response format makes it easier to work with the data on the frontend(example, an array with objects representing the data for each index).

**Comment by xbgmsharp** [comment]
I try to setup an API with only the Nodes or the Indices using the ES cat api.
https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html
``/_cat/indices?format=json&pretty``
and 
``/_cat/nodes?format=json&pretty``

However the backend is in Java and I must admit it is out of my knowledge.
I would suggest you merge both PR #7 and #17 so we can have have indices page and nodes page. Then you can make the backend call. 

In the meantime i implemented the sorting command.

**Comment by adamlepkowski** [comment]
@xbgmsharp Have you made this new api method?  Regarding the pull request you can merge my repository to your and then make one PR ;)

**Comment by xbgmsharp** [comment]
@adamlepkowski, I didn't make the API method. If you could do so it would great, I found the ES call. However I can merge both PR into one and add sorting feature.

**Comment by xbgmsharp** [comment]
Closing add sorting via #28.

**Pull request closed without merging**
