### PR TITLE
Add LDAP group search

### PR DESCRIPTION
**Pull request by moliware**
Hi,

Based on #154 (and its comments) I implemented group search for ldap. This means that if you set `auth.settings.group-search.group` or en var `LDAP_GROUP` it will check if the user belongs to a group by doing an ldap search.

I also started using environment variable to define this properties so that it's more docker friendly.

Thank you!

### CODE REVIEW

**Comment by Jac2NL** [comment]
This is something I could use too.

**Comment by alexjfisher** [comment]
Without this or similar change, the ldap feature isn't usable by many organisations.  It's quite common for all users to be under the same DN.  We need a way to restrict access otherwise I may as well turn authentication off completely.

Perhaps the implementation should be more generic though??  Perhaps expose 'search-filter' directly with examples for how you'd configure these to restrict by group in AD/OpenLDAP/FreeIPA etc?

**Comment by alexjfisher** [comment]
@lmenezes Any chance of this getting reviewed and merged?

**Comment by rtkgjacobs** [comment]
+1

**Comment by kn0x1c** [comment]
Would use cerebro in production, but this feature is blocking it...

**Comment by kobaan** [comment]
+1

**Comment by Chrobak77** [comment]
> Hi,
> 
> Based on #154 (and its comments) I implemented group search for ldap. This means that if you set `auth.settings.group-search.group` or en var `LDAP_GROUP` it will check if the user belongs to a group by doing an ldap search.
> 
> I also started using environment variable to define this properties so that it's more docker friendly.
> 
> Thank you!

Hi!
I've provided some feedback at
https://github.com/lmenezes/cerebro/pull/154#issuecomment-444964596
Would love to hear from you.
Take care

**Pull request merged**
