### PR TITLE
Allow to configure the base path

### LINKED ISSUE #48: Support custom location
I'd like to use cerebro under custom location, i.e. `/cerebro`.

I have configured nginx to proxy-pass requests from `/cerebro` to `cerebro` upstream, but it doesn't support custom locations and tries to fetch hosts using root location: `/connect/hosts`

P.S. Custom `routes` file doesn't help.

### PR DESCRIPTION
**Pull request by champtar**
This needs testing
fixes #48

### CODE REVIEW

**Comment by chaitanyabhasme** [comment]
@champtar I needed the base path feature and your changes work for me. I was trying to package the changes using sbt and use it with cerebro install but couldnt that to work. How can I build the project zip and run cerebro with these changes?

**Comment by champtar** [comment]
Hi @chaitanyabhasme 
I didn't tried to package it for now
@lmenezes, how do you package?

**Comment by Tonyko** [comment]
@champtar  `sbt dist`

**Comment by lmenezes** [comment]
@champtar hey, thanks for the PR. I haven't had much time lately, but I will test this and merge if all is ok during this weekend :)

**Comment by champtar** [comment]
Hi @lmenezes, no worries, i've just rebased my commits on top of 0.6.0
@Tonyko thanks

**Comment by lmenezes** [comment]
@champtar this seems to work fine, thanks :)

**Comment by iamlennym** [comment]
Hi guys,

My Config:

_# NGINX Config - Upstream_
**upstream Consumer_cerebro {
        server 10.0.0.12:19000 fail_timeout=0;
}**

_# NGINX Config - Location_
**location ~ (^/Consumer_cerebro/) {
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-Proto https;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite  ^/Consumer_cerebro/(.*)  /$1 break;
        proxy_pass          http://Consumer_cerebro;
    }**


_Cerebro application.conf file_
**# Application base path
basePath = "/Consumer_cerebro/"**


I am configuring an instance of cerebro behind NGINX, but I am struggling to get the basePath configured correctly. Can someone please indicate what I am missing here?

With the above configuration, the login page is displayed correctly, but as soon as I type in my credentials and hit the login button, I get a NGINX 404 Not found with the URL path = /auth/login
(without the /Consumer_cerebro/)

Version of cerebro used: 0.6.3
thanks,
Leendert.

**Comment by kub1x** [comment]
@iamlennym Just delete `basePath` setting from cerebro and use only the rewrite rule. 

I also wanted to use basePath functionality of Cerebro, but it did not work for me. Even on the login page it kept requesting /app.css, etc. Realized from @iamlennym's post, that nginx can do all the job.

**Comment by champtar** [comment]
My config, in `/etc/cerebro/application.conf`
```
play.http.context="/cerebro/"
```

and in nginx:
```
location /cerebro/ {
    auth_basic           "MDP-cerebro";
    auth_basic_user_file /etc/nginx/conf.d/htpasswd-cerebro;
    proxy_pass http://127.0.0.1:9001;
}
```

**Comment by kub1x** [comment]
@champtar Heureka.. for anyone who reads all the way down here, **don't forget the trailing slash** ;) It can be omitted in the nginx conf, but in Cerebro it leads to 404. Thanks

**Pull request merged**
