### PR TITLE
show host in nodes overview

### LINKED ISSUE #345: nodes overview shows no ip/host
to replicate: go to nodes overview (not index overview) and check the most left column. IP/Host is not shown.

image

### PR DESCRIPTION
**Pull request by drummerwolli**
fixes #345 
before:

image

after:

image

### CODE REVIEW

**Comment by drummerwolli** [comment]
@lmenezes any chance to get this merged and released soonish?

**Comment by drummerwolli** [comment]
@lmenezes any updates? feedback?

**Comment by drummerwolli** [comment]
@lmenezes @moliware any chance to get this merged? would this fix this issue? please review

**Comment by moliware** [comment]
Just checked it, and it indeed fixes the problem.

Thank you

**Pull request merged**
